import type { Route } from '@playwright/test'
import assert from 'node:assert/strict'
import { expect, test } from '@playwright/test'
import { CONVERSATION_ID, installApiRoutes, installBrowserStubs } from './fixtures'

const json = (data: unknown) => ({ json: { success: true, code: 0, data } })

test('模型下拉在途重复打开只读取一次，loading 与失败重试可见，完成后再次打开仍刷新', async ({ page }) => {
  await installApiRoutes(page, () => [])
  await installBrowserStubs(page, { lines: [], holdBeforeIndex: -1 })
  const requests: Route[] = []
  await page.route('**/api/llm/models', (route) => {
    requests.push(route)
  })
  await page.goto('/workspace')
  // Reka modal 菜单打开时会将外部节点 aria-hidden；仍需观察触发按钮的 loading 属性。
  const trigger = page.getByRole('button', { name: '选择模型与思考强度', includeHidden: true })
  await expect(trigger).toHaveAttribute('aria-busy', 'true')
  await trigger.click()
  await expect(page.getByRole('status').filter({ hasText: '正在读取模型…' })).toBeVisible()
  await page.keyboard.press('Escape')
  await trigger.click()
  await expect.poll(() => requests.length).toBe(1)
  await requests[0]!.fulfill({ status: 503, json: { success: false, message: '模型服务暂时不可用' } })
  await expect(trigger).toHaveAttribute('aria-busy', 'false')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('status').filter({ hasText: '模型服务暂时不可用' })).toBeVisible()
  await trigger.click()
  await expect.poll(() => requests.length).toBe(2)
  await expect(trigger).toHaveAttribute('aria-busy', 'true')
  const model = { id: 'model-a', displayName: '恢复的模型', reasoningEffort: null, reasoningEffortOptions: [], isDefault: true }
  await requests[1]!.fulfill(json([model]))
  await expect(trigger).toHaveAttribute('aria-busy', 'false')
  await expect(trigger).toContainText('恢复的模型')
  await expect(page.getByRole('status').filter({ hasText: '模型服务暂时不可用' })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await trigger.click()
  await expect.poll(() => requests.length).toBe(3)
  await requests[2]!.fulfill(json([model]))
  await expect(trigger).toHaveAttribute('aria-busy', 'false')
})

test('会话改名与删除显示 pending，重复操作被禁止，失败后保留会话并可重试', async ({ page }) => {
  await installApiRoutes(page, () => [])
  await installBrowserStubs(page, { lines: [], holdBeforeIndex: -1 })
  const requests: Route[] = []
  await page.route(`**/api/conversations/${CONVERSATION_ID}`, (route) => {
    requests.push(route)
  })
  await page.goto('/workspace')
  const chat = page.getByRole('button', { name: '落地页 SEO 诊断', exact: true })
  const options = page.getByRole('button', { name: '对话选项', exact: true })
  await options.click()
  await page.getByRole('button', { name: '重命名', exact: true }).click()
  const input = page.getByRole('textbox', { name: '重命名', exact: true })
  await input.fill('新的标题')
  await input.press('Enter')
  await expect(chat).toHaveAttribute('aria-busy', 'true')
  await expect(options).toBeDisabled()
  await options.evaluate((button: HTMLButtonElement) => {
    button.click()
    button.click()
  })
  await expect.poll(() => requests.length).toBe(1)
  assert.equal(requests[0]!.request().method(), 'PATCH')
  await requests[0]!.fulfill({ status: 503, json: { success: false, message: '改名失败，请重试' } })
  await expect(page.getByText('改名失败，请重试', { exact: true })).toBeVisible()
  await expect(options).toBeEnabled()
  await expect(chat).not.toHaveAttribute('aria-busy', 'true')
  await options.click()
  await page.getByRole('button', { name: '重命名', exact: true }).click()
  await input.fill('新的标题')
  await input.press('Enter')
  await expect.poll(() => requests.length).toBe(2)
  await requests[1]!.fulfill(json({ id: CONVERSATION_ID, title: '新的标题', createdAt: '2026-08-16T08:00:00.000Z', updatedAt: '2026-08-16T09:00:00.000Z' }))
  const renamed = page.getByRole('button', { name: '新的标题', exact: true })
  await expect(renamed).toBeVisible()
  await options.click()
  await page.getByRole('button', { name: '删除对话', exact: true }).click()
  await expect(renamed).toHaveAttribute('aria-busy', 'true')
  await expect(options).toBeDisabled()
  await expect.poll(() => requests.length).toBe(3)
  assert.equal(requests[2]!.request().method(), 'DELETE')
  await requests[2]!.fulfill({ status: 503, json: { success: false, message: '删除失败，请重试' } })
  await expect(page.getByText('删除失败，请重试', { exact: true })).toBeVisible()
  await expect(options).toBeEnabled()
  await options.click()
  await page.getByRole('button', { name: '删除对话', exact: true }).click()
  await expect.poll(() => requests.length).toBe(4)
  await requests[3]!.fulfill(json({ id: CONVERSATION_ID, deleted: true }))
  await expect(renamed).toHaveCount(0)
})

test('退出登录在请求与导航期间保持 loading，失败后恢复而不假装退出', async ({ page }) => {
  await installApiRoutes(page, () => [])
  await installBrowserStubs(page, { lines: [], holdBeforeIndex: -1 })
  const requests: Route[] = []
  await page.route('**/api/auth/logout', (route) => {
    requests.push(route)
  })
  await page.goto('/workspace')
  await page.getByRole('button', { name: '用户设置', exact: true }).click()
  const logout = page.getByRole('menuitem', { name: '退出登录', exact: true })
  await logout.click()
  await expect(logout).toHaveAttribute('aria-busy', 'true')
  await expect(logout).toBeDisabled()
  await expect.poll(() => requests.length).toBe(1)
  await requests[0]!.fulfill({ status: 503, json: { success: false, message: 'offline' } })
  await expect(logout).toHaveAttribute('aria-busy', 'false')
  await expect(logout).toBeEnabled()
  assert.equal(new URL(page.url()).pathname, '/workspace')
  await logout.click()
  await expect.poll(() => requests.length).toBe(2)
  await requests[1]!.fulfill(json(null))
  await expect(page).toHaveURL('/')
})
